// 세로
export const portraitComponents = [
  "NewCertificateType5",
  "NewCertificateType6",
  "NewCertificateType6Single",
  "NewCertificateType9",
  "NewCertificateType15",
  "NewEmptyPortraitCertificate",
];

// 가로
export const landscapeComponents = [
  "NewCertificateType1",
  "NewCertificateType2",
  "NewCertificateType3",
  "NewCertificateType4",
  "NewCertificateType7",
  "NewCertificateType7Single",
  "NewCertificateType8",
  "NewCertificateType10",
  "NewCertificateType11",
  "NewCertificateType12",
  "NewCertificateType13",
  "NewCertificateType14",
  "NewCertificateType16",
  "NewCertificateType17",
  "NewCertificateType18",
  "NewCertificateType19",
  "NewCertificateType20",
  "NewCertificateType21",
  "NewCertificateType22",
  "NewCertificateType23",
  "NewCertificateType24",
  "NewCertificateType25",
  "NewCertificateType26",
  "NewCertificateType27",
  "NewCertificateType29",
  "NewCertificateType30",
  "NewCertificateType31",
  "NewCertificateType32",
  "NewCertificateType33",
  "NewCertificateType34",
  "NewEmptyLandscapeCertificate",
];
